name: PlateToGrow Backend

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: placetogrow
          MYSQL_USER: root
          MYSQL_PASSWORD: ''
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, pdo_mysql

    - name: Copy .env
      run: echo "$APP_ENV" > .env

    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-scripts --no-progress --no-interaction

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run Database Migrations
      run: php artisan migrate --force

    - name: Execute Tests
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: placetogrow
        DB_USERNAME: root
        DB_PASSWORD: ''
      run: php artisan test --parallel
